# Generated by Django 4.1 on 2023-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_guesser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.TextField(default='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='date_used',
            field=models.DateTimeField(null=True),
        ),
    ]
